/*-----------------------------------
Author: Marco Rouge / Andrin Kälin
Arbeit: Hypnos
Thema: Accelerometer Test
Datum: 14.11.2020
-------------------------------------*/

#include <stm32l431xx.h>
#include "system_init.h"
#include "GPIO.h"
#include "I2C.h"

#define BIO_slv_add	0x62
#define ACC_slv_add 0x1C

unsigned char buffer = 0;

void Buttons_init(void);
void TIM6_init(void);
void BIO_init(void);
void ACC_init(void);

int main(void)	//main
{	
	system_clock_init();	//Initiliaze RCC and clocks
	GPIO_init();
	I2C_init();
	Buttons_init();
	TIM6_init();
	BIO_init();
	ACC_init();
	while(1)	//endless loop
	{

	}
}

void Buttons_init(void)
{
	GPIOA ->MODER &= ~(GPIO_MODER_MODE0 | GPIO_MODER_MODE1);	//Configure PA0 and PA1 as Input
	GPIOA ->PUPDR &= ~(GPIO_PUPDR_PUPD0 | GPIO_PUPDR_PUPD1);	//No pull up or pull down	
	
	SYSCFG ->EXTICR[0] &= ~(SYSCFG_EXTICR1_EXTI0_Msk | SYSCFG_EXTICR1_EXTI1_Msk);	//Line Mapping
	
	EXTI ->IMR1 |= (EXTI_IMR1_IM0 | EXTI_IMR1_IM1);	//Unmask PA0 and PA1 for Interrupt line
	EXTI ->RTSR1 |= (EXTI_RTSR1_RT0 | EXTI_RTSR1_RT1);	//Detect rising edge
	
	
	NVIC_EnableIRQ(EXTI0_IRQn);	//Enable interrupt for EXTI0
	NVIC_EnableIRQ(EXTI1_IRQn);	//Enable interrupt for EXTI1
}
void TIM6_init(void)
{
	RCC ->APB1ENR1 |= RCC_APB1ENR1_TIM6EN;
	
	TIM6 ->CR1 |= (TIM_CR1_OPM | TIM_CR1_URS);	//OPM Mode, Interrupt only generated by Counter over- underflow
	TIM6 ->DIER |= TIM_DIER_UIE;
	TIM6 ->PSC |= 0x9C40;	//Prescaler division = 40'000 * 1/80MHz -> 50uS per Cycle
	TIM6 ->ARR |= 0x3E8; //Counter stops after 500ms
	
	TIM6 ->EGR |= TIM_EGR_UG;	//Generate update event to initialize registers	
	
	NVIC_EnableIRQ(TIM6_IRQn);	//Enable interrupt for TIM6
}

void BIO_init(void)
{
	
	set_LDO_EN;
	I2C_start_com(2,BIO_slv_add,0);	//Start I2C2 communication
	I2C_write(0x0A);					
	I2C_write(0x2A);
	I2C_stop_com();		//WRITE 0x2A to Adress 0x0A configures the FIFO 

	I2C_start_com(2,BIO_slv_add,0);	//Start I2C2 communication
	I2C_write(0x10);					
	I2C_write(0x80);
	I2C_stop_com();
		
	I2C_start_com(7,BIO_slv_add,0);	//Start I2C2 communication
	I2C_write(0x20);					
	I2C_write(0x21);
	I2C_write(0x93);
	I2C_write(0x00);
	I2C_write(0x0F);
	I2C_write(0x0F);
	I2C_write(0x0F);
	I2C_stop_com(); //configures the  LED sequence Registers	
}

void ACC_init(void)
{
	//Enable Interrupt 1 of Accelerometer
	GPIOA ->MODER &= ~(GPIO_MODER_MODE2);	//Configure PA2 in input mode
	GPIOA ->PUPDR &= ~(GPIO_PUPDR_PUPD2);	//Reset PUPDR of PA2
	GPIOA ->PUPDR |= GPIO_PUPDR_PUPD2_0;	//Set Pull Up Resistor for PA2
	
	SYSCFG ->EXTICR[0] &= ~(SYSCFG_EXTICR1_EXTI2_Msk);	//Map PA2 to EXTI2
	
	EXTI ->IMR1 |= EXTI_IMR1_IM2;	//Unmask external interrupt line 2 (EXTI2)
	EXTI ->FTSR1 |= EXTI_FTSR1_FT2;	//Detect falling edge on EXTI2
	
	NVIC_EnableIRQ(EXTI2_IRQn);	//Enable interrupt for EXTI2

	//Configure Accelerometer
	
	//Set ACC into standby power mode, 100Hz sample rate
	I2C_start_com(2,ACC_slv_add,0);
	I2C_write(0x2A);
	I2C_write(0x1C);
	I2C_stop_com();
	
	//Set ACC in Low Noise Low Power oversampling mode
	I2C_start_com(2,ACC_slv_add,0);
	I2C_write(0x2B);
	I2C_write(0x01);
	I2C_stop_com();
	
	//Configure Transient detection control register
	I2C_start_com(2,ACC_slv_add,0);
	I2C_write(0x1D);
	I2C_write(0x0E);
	I2C_stop_com();
	
	//Configure Transient threshold register
	I2C_start_com(2,ACC_slv_add,0);
	I2C_write(0x1F);
	I2C_write(0x07);
	I2C_stop_com();
	
	//Configure Transient counter register
	I2C_start_com(2,ACC_slv_add,0);
	I2C_write(0x20);
	I2C_write(0x0A);
	I2C_stop_com();
	
	//Enable ACC Transient detection interrupt
	I2C_start_com(2,ACC_slv_add,0);
	I2C_write(0x2D);
	I2C_write(0x20);
	I2C_stop_com();
	
	//Enable ACC interrupt 1
	I2C_start_com(2,ACC_slv_add,0);
	I2C_write(0x2E);
	I2C_write(0x20);
	I2C_stop_com();
	
	//Put ACC into active mode
	I2C_start_com(2,ACC_slv_add,0);
	I2C_write(0x2A);
	I2C_write(0x1D);
	I2C_stop_com();
	
}

void EXTI0_IRQHandler(void)
{
	set_LDO_EN;
	EXTI ->PR1 &= ~(EXTI_PR1_PIF0);
}

void EXTI1_IRQHandler(void)
{
	reset_LDO_EN;
	EXTI ->PR1 &= ~(EXTI_PR1_PIF1);
}

void EXTI2_IRQHandler(void)
{
	set_motor_ctrl;
	TIM6 ->EGR |= TIM_EGR_UG;
	TIM6 ->CR1 |= TIM_CR1_CEN;
	
	I2C_start_com(1,ACC_slv_add,0);
	I2C_write(0x1E);
	I2C_start_com(1,ACC_slv_add,1);
	buffer = I2C_read();
	I2C_stop_com();
	
	I2C_start_com(1,ACC_slv_add,0);
	I2C_write(0x0C);
	I2C_start_com(1,ACC_slv_add,1);
	buffer = I2C_read();
	I2C_stop_com();
	
	EXTI ->PR1 &= ~(EXTI_PR1_PIF2);
	NVIC_ClearPendingIRQ(EXTI2_IRQn);
}

void TIM6_IRQHandler(void)
{
	reset_motor_ctrl;
	TIM6 ->SR &= ~(TIM_SR_UIF);
}
